import {depositTotal,outstanding,stashBreakdown,financeMoney as money} from './finance-model.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=value=>new Date(value.length===10?value+'T12:00:00':value).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
export async function mountFinance(root,session,{request,onSaved,onClean,canRefresh}){
  let state,history=false,confirm=null,submissionId=crypto.randomUUID(),message='';
  const mode=root.dataset.financeMode,own=()=>state.deposits.filter(e=>e.userId===session.user.id);
  const error=e=>{message=e.message;const node=root.querySelector('[data-finance-message]');if(node)node.textContent=message;};
  const canLoad=()=>root.isConnected&&!root.busy&&!confirm&&canRefresh();
  root.refreshFromServer=async()=>{if(!canLoad())return false;const fresh=await request('/api/finance');if(!canLoad())return false;state=fresh;root.seenRevision=fresh.revision;root.seenDay=fresh.day;render();return true;};
  async function save(path,body){
    if(root.busy)return;root.busy=true;root.querySelectorAll('button,input,textarea').forEach(el=>el.disabled=true);message='';
    try{state=await request(path,{method:'POST',body});root.seenRevision=state.revision;root.seenDay=state.day;confirm=null;submissionId=crypto.randomUUID();await onSaved();render();}
    catch(e){error(e);}finally{root.busy=false;root.querySelectorAll('button,input,textarea').forEach(el=>el.disabled=false);root.querySelectorAll('[data-finance-quantity]').forEach(input=>input.disabled=!state.bands.find(b=>b.id===input.dataset.financeQuantity)?.price);}
  }
  const entry=(e,review=false)=>{
    const payout=state.payouts.find(p=>p.id===e.payoutId);
    return `<details class="finance-entry"><summary><span><strong>${esc(e.name)}</strong><small>${date(e.at)} · ${e.lines.reduce((n,l)=>n+l.quantity,0).toLocaleString()} bands</small></span><span class="finance-entry-value"><strong>${money(depositTotal(e))}</strong><small class="finance-state ${e.status}">${e.status==='pending'?'Awaiting payout':e.status==='paid'?'Paid':'Rejected'}</small></span></summary><div class="finance-entry-body">${e.lines.map(l=>`<div class="finance-line"><span>${esc(l.name)} <small>× ${l.quantity.toLocaleString()} at ${money(l.price)}</small></span><strong>${money(l.quantity*l.price)}</strong></div>`).join('')}${e.notes?'<p>'+esc(e.notes)+'</p>':''}${payout?'<p class="finance-receipt">Payment confirmed by '+esc(payout.byName)+' · '+date(payout.at)+'</p>':''}${e.status==='rejected'?'<p class="finance-receipt">Rejected by '+esc(e.reviewedByName)+' · '+date(e.reviewedAt)+'<br>'+esc(e.reason)+'</p>':''}${review&&state.canManage&&e.status==='pending'?'<button class="text-button" data-finance-reject="'+esc(e.id)+'">Reject incorrect entry</button>':''}</div></details>`;
  };
  function breakdown(entries){
    const saved=stashBreakdown(entries),rows=[...state.bands.map(b=>saved.find(s=>s.id===b.id)||{...b,quantity:0,amount:0}),...saved.filter(s=>!state.bands.some(b=>b.id===s.id))];
    return `<div class="stash-breakdown" role="table" aria-label="Unpaid stash by band type"><div class="stash-breakdown-row stash-breakdown-head" role="row"><span role="columnheader">Band type</span><span role="columnheader">Quantity</span><span role="columnheader">Value</span></div>${rows.map(b=>`<div class="stash-breakdown-row" role="row"><span role="cell"><i class="finance-band-dot" style="background:${b.color}"></i>${esc(b.name)}</span><strong role="cell">${b.quantity.toLocaleString()}</strong><span role="cell">${money(b.amount)}</span></div>`).join('')}</div>`;
  }
  function ownPage(){
    const entries=own(),owed=outstanding(entries),paid=state.payouts.filter(p=>p.userId===session.user.id).reduce((sum,p)=>sum+p.amount,0),priced=state.bands.some(b=>b.price>0);
    return `<div class="page-heading"><div><h1>My stash</h1><p>Your own bands and unpaid balance. Only you and authorized finance staff can see these amounts.</p></div>${state.canViewLedger?'<button class="button secondary" data-page="history">Open treasury →</button>':''}</div>
    <section class="finance-balance"><div><span class="finance-eyebrow">STILL OWED TO YOU</span><strong>${money(owed)}</strong><p>${entries.filter(e=>e.status==='pending').length} deposit${entries.filter(e=>e.status==='pending').length===1?'':'s'} awaiting payment</p></div><div class="finance-paid-total"><span>Paid to date</span><strong>${money(paid)}</strong><small>Your payment history stays below.</small></div></section>
    <section class="panel finance-stash-summary"><h2>Your unpaid stash</h2>${breakdown(entries)}</section><div class="finance-layout"><section class="panel finance-form-panel"><h2>Record stashed bands</h2><div class="finance-account"><span class="finance-avatar">${esc(state.user.name.split(' ').map(n=>n[0]).slice(0,2).join(''))}</span><div><strong>${esc(state.user.name)}</strong><small>Your signed-in account${state.user.stateId?' · State ID '+esc(state.user.stateId):''}</small></div></div>
    <form id="finance-deposit-form"><div class="finance-quantity-head"><span>BAND / RATE</span><span>STASHED</span></div>${state.bands.map(b=>`<div class="finance-quantity-row"><label for="finance-qty-${esc(b.id)}"><span class="finance-band-dot" style="background:${b.color}"></span><span>${esc(b.name)}<small>${b.price?money(b.price)+' each':'Rate not set'}</small></span></label><input id="finance-qty-${esc(b.id)}" aria-label="${esc(b.name)} stashed" data-finance-quantity="${esc(b.id)}" type="number" min="0" max="1000000" step="1" value="0" inputmode="numeric" ${b.price?'':'disabled'}></div>`).join('')}
    ${!priced?'<p class="finance-help">An admin needs to set band rates in Settings before deposits can be recorded.</p>':''}${session.permissions.settings==='manage'?'<button class="text-button finance-rate-link" type="button" data-page="settings">Manage band rates →</button>':''}<label for="finance-note">Stash note <span class="muted">(optional)</span></label><textarea id="finance-note" rows="2" maxlength="2000" placeholder="Where you left them, or anything the finance team should know"></textarea><div class="finance-deposit-total"><span>This deposit</span><strong data-finance-total>$0</strong></div><button class="button primary" type="submit" ${priced?'':'disabled'}>Save my deposit</button><p class="finance-help">The value is added to your outstanding balance. A finance manager confirms payment after paying you in game.</p></form></section>
    <section class="panel finance-history"><div class="finance-section-head"><h2>Your deposits</h2><div class="tabs"><button data-finance-history="pending" class="${history?'':'selected'}">Outstanding</button><button data-finance-history="history" class="${history?'selected':''}">History</button></div></div><div data-finance-entries>${ownEntries()}</div></section></div>`;
  }
  function ownEntries(){const rows=own().filter(e=>history?e.status!=='pending':e.status==='pending');return rows.length?rows.map(e=>entry(e)).join(''):`<div class="finance-empty"><h3>${history?'No settled deposits yet.':'You’re all caught up.'}</h3><p>${history?'Paid and rejected entries will stay here for reference.':'New deposits appear here until a finance manager confirms your payout.'}</p></div>`;}
  function ledgerPage(){
    const pending=state.deposits.filter(e=>e.status==='pending'),groups=[...new Set(pending.map(e=>e.userId))].map(id=>({id,name:pending.find(e=>e.userId===id).name,entries:pending.filter(e=>e.userId===id)})),unpaid=state.bills.filter(b=>b.status!=='paid'),due=unpaid.filter(b=>b.status==='due'||b.status==='overdue'),next=unpaid.filter(b=>b.status==='upcoming');
    return `<div class="page-heading"><div><h1>Treasury</h1><p>See each member’s unpaid stash by band type, confirm payouts, and cover Thursday bills.</p></div>${state.canSubmit?'<button class="button secondary" data-page="overview">My stash →</button>':''}</div><section class="finance-balance finance-ledger-balance"><div><span class="finance-eyebrow">MEMBER PAYOUTS WAITING</span><strong>${money(outstanding(pending))}</strong><p>${groups.length} member${groups.length===1?'':'s'} · ${pending.length} deposit${pending.length===1?'':'s'}</p></div><div class="finance-paid-total"><span>House + gang taxes</span><strong>$10,000 <small>/ week</small></strong><small>Every Thursday · Central time</small></div></section>
    <section class="panel finance-stash-summary"><h2>Total unpaid stash</h2><p class="finance-help">All members combined. Values use each deposit’s saved rate.</p>${breakdown(pending)}</section><div class="finance-layout"><section class="panel finance-history"><div class="finance-section-head"><h2>Awaiting payout</h2><span class="finance-count">${groups.length}</span></div>${groups.length?groups.map(g=>`<article class="finance-person"><div class="finance-person-head"><div><h3>${esc(g.name)}</h3><p>${g.entries.length} stashed deposit${g.entries.length===1?'':'s'}</p></div><strong>${money(outstanding(g.entries))}</strong></div>${breakdown(g.entries)}<details class="finance-deposit-receipts"><summary>View ${g.entries.length} deposit receipts</summary>${g.entries.map(e=>entry(e,true)).join('')}</details>${state.canManage?(g.id===session.user.id&&!session.user.owner?'<p class="finance-help">Another finance manager must confirm your payout.</p>':'<button class="button primary" data-finance-pay="'+esc(g.id)+'">Confirm paid '+money(outstanding(g.entries))+'</button>'):''}</article>`).join(''):'<div class="finance-empty"><h3>No payouts waiting.</h3><p>Member deposits appear here automatically.</p></div>'}</section>
    <section class="panel finance-bills"><div class="finance-section-head"><h2>Thursday bills</h2><span class="finance-count">$10,000</span></div><p class="finance-help">Tracking from ${date(state.startDate)}. Unpaid weeks carry forward.</p>${due.length?'<div class="finance-due">'+money(due.reduce((n,b)=>n+b.amount,0))+' due or overdue</div>':''}${[...due,...next].map(b=>`<div class="finance-bill"><div><strong>${esc(b.name)}</strong><small>Thursday, ${date(b.dueDate)} · ${b.status==='upcoming'?'Upcoming':b.status==='overdue'?'Overdue':'Due today'}</small></div><strong>${money(b.amount)}</strong>${state.canManage?'<button class="button secondary" data-finance-bill="'+esc(b.kind)+'" data-due-date="'+b.dueDate+'">Confirm paid</button>':''}</div>`).join('')||'<div class="finance-empty"><h3>This week is covered.</h3><p>The next bills appear automatically.</p></div>'}<details class="finance-bill-history"><summary>Weekly payment history (${state.bills.filter(b=>b.status==='paid').length})</summary>${state.bills.filter(b=>b.status==='paid').sort((a,b)=>b.dueDate.localeCompare(a.dueDate)).map(b=>'<div class="finance-bill"><div><strong>'+esc(b.name)+' · '+money(b.amount)+'</strong><small>For '+date(b.dueDate)+'<br>Confirmed by '+esc(b.byName)+' · '+date(b.at)+'</small></div></div>').join('')||'<p>No weekly payments recorded yet.</p>'}</details></section></div>
    <section class="panel finance-history finance-settled"><div class="finance-section-head"><h2>Paid & reviewed history</h2><span>${state.deposits.filter(e=>e.status!=='pending').length} deposits</span></div>${state.deposits.filter(e=>e.status!=='pending').map(e=>entry(e)).join('')||'<div class="finance-empty"><p>Paid entries leave the queue and stay here with their payment confirmation.</p></div>'}</section>`;
  }
  function confirmation(){
    if(!confirm)return '';
    const reject=confirm.kind==='reject',label=reject?'Reject this deposit':confirm.kind==='bill'?'Confirm weekly payment':'Confirm member payout';
    return `<section class="finance-confirm panel" aria-label="${label}"><h2>${label}</h2><p>${esc(confirm.description)}</p><form id="finance-confirm-form">${reject?'<label for="finance-reason">Reason</label><textarea id="finance-reason" required maxlength="500" rows="2" placeholder="Explain what needs to be corrected"></textarea>':'<p>This records a payment already made in game.</p>'}<div class="finance-confirm-actions"><button class="button primary" type="submit">${reject?'Reject deposit':'Yes, payment has been made'}</button><button class="button secondary" type="button" data-finance-cancel>Cancel</button></div></form></section>`;
  }
  function render(){
    if(!root.isConnected)return;
    root.innerHTML=`<div class="form-error" data-finance-message role="alert">${esc(message)}</div><div data-finance-confirm>${confirmation()}</div>${mode==='bands'?ownPage():ledgerPage()}`;
    bind();
  }
  function showConfirm(value){confirm=value;root.querySelector('[data-finance-confirm]').innerHTML=confirmation();bindConfirmation();root.querySelector('[data-finance-confirm]').scrollIntoView({block:'nearest'});root.querySelector('#finance-confirm-form button')?.focus();}
  function bindConfirmation(){
    root.querySelector('[data-finance-cancel]')?.addEventListener('click',()=>{confirm=null;onClean();root.querySelector('[data-finance-confirm]').innerHTML='';});
    root.querySelector('#finance-confirm-form')?.addEventListener('submit',e=>{e.preventDefault();const c=confirm;save(c.path,{...c.body,...(c.kind==='reject'?{decision:'reject',reason:root.querySelector('#finance-reason').value}: {})});});
  }
  function bind(){
    const form=root.querySelector('#finance-deposit-form');
    form?.addEventListener('input',()=>{let total=0;form.querySelectorAll('[data-finance-quantity]').forEach(input=>{const b=state.bands.find(b=>b.id===input.dataset.financeQuantity),q=Number(input.value);total+=b.price*(Number.isFinite(q)?q:0);});root.querySelector('[data-finance-total]').textContent=money(total);});
    form?.addEventListener('submit',e=>{e.preventDefault();const lines=[...form.querySelectorAll('[data-finance-quantity]')].filter(i=>Number(i.value)>0).map(i=>({id:i.dataset.financeQuantity,quantity:Number(i.value)}));if(!lines.length){error(Error('Enter at least one stashed band.'));return;}save('/api/finance/deposits',{requestId:submissionId,ratesVersion:state.ratesVersion,lines,notes:root.querySelector('#finance-note').value});});
    root.querySelectorAll('[data-finance-history]').forEach(button=>button.onclick=()=>{history=button.dataset.financeHistory==='history';root.querySelectorAll('[data-finance-history]').forEach(b=>b.classList.toggle('selected',(b.dataset.financeHistory==='history')===history));root.querySelector('[data-finance-entries]').innerHTML=ownEntries();});
    root.querySelectorAll('[data-finance-pay]').forEach(button=>button.onclick=()=>{const entries=state.deposits.filter(e=>e.userId===button.dataset.financePay&&e.status==='pending'),amount=outstanding(entries);showConfirm({kind:'payout',description:money(amount)+' to '+entries[0].name+' for '+entries.length+' deposit'+(entries.length===1?'':'s')+'. These entries will move to paid history.',path:'/api/finance/payouts',body:{requestId:crypto.randomUUID(),userId:button.dataset.financePay,expectedOutstanding:amount,expectedEntryIds:entries.map(e=>e.id)}});});
    root.querySelectorAll('[data-finance-bill]').forEach(button=>button.onclick=()=>{const b=state.bills.find(b=>b.kind===button.dataset.financeBill&&b.dueDate===button.dataset.dueDate);showConfirm({kind:'bill',description:money(b.amount)+' for '+b.name+' due '+date(b.dueDate)+'.',path:'/api/finance/bills',body:{requestId:crypto.randomUUID(),kind:b.kind,dueDate:b.dueDate}});});
    root.querySelectorAll('[data-finance-reject]').forEach(button=>button.onclick=()=>{const e=state.deposits.find(e=>e.id===button.dataset.financeReject);showConfirm({kind:'reject',description:e.name+' · '+money(depositTotal(e))+'. The member will see your reason in their history.',path:'/api/finance/deposits/'+e.id,body:{}});});
    bindConfirmation();
  }
  try{state=await request('/api/finance');if(!root.isConnected)return;root.seenRevision=state.revision;root.seenDay=state.day;render();}catch(e){root.innerHTML='<p class="notice error">'+esc(e.message)+'</p>';}
}
