import {depositTotal,outstanding,stashBreakdown,financeMoney as money,nextThursday} from './finance-model.js';
import {readDraft,saveDraft,clearDraft} from './draft-store.js';
import {escapeHtml as esc,timestamp,dayLabel,downloadCsv} from './ui-utils.js';
export async function mountFinance(root,session,{request,onSaved,onClean,canRefresh}){
  let state,tab='payouts',history='add',confirm=null,message='',filter='',statusFilter='all',from='',to='',limit=20,filtersOpen=false;
  const memberId=session.user.id,mode=root.dataset.financeMode;
  let draft=readDraft(memberId)||{quantities:{},notes:'',requestId:crypto.randomUUID()},draftStored=true;
  const own=()=>state.deposits.filter(e=>e.userId===memberId);
  const hasDraft=()=>Object.values(draft.quantities).some(v=>Number(v)>0)||!!draft.notes;
  const notice=()=>root.querySelector('[data-finance-message]');
  function error(e){message=e.message;const n=notice();if(n){n.hidden=false;n.textContent=message;n.scrollIntoView({block:'nearest'});}}
  const canLoad=()=>root.isConnected&&!root.busy&&!confirm&&canRefresh();
  root.seenAccounts=session.versions?.accounts;
  root.openReceipt=id=>{const e=state?.deposits.find(e=>e.id===id);if(!e)return;history=e.status==='pending'?'pending':'history';tab='transactions';filter=id;statusFilter='all';from='';to='';limit=20;render();const card=root.querySelector('[data-receipt-id="'+CSS.escape(id)+'"]');if(card){card.querySelector('details').open=true;card.scrollIntoView({block:'nearest'});}};
  function seen(){root.seenRevision=state.revision;root.seenDay=state.day;}
  root.refreshFromServer=async()=>{if(!canLoad())return false;const fresh=await request('/api/finance');if(!canLoad())return false;const focus=document.activeElement?.id,selection=document.activeElement?.selectionStart;if(mode==='bands'&&hasDraft()&&fresh.ratesVersion!==state.ratesVersion){fresh.bands=state.bands;fresh.ratesVersion=state.ratesVersion;message='Band rates changed. Your quantities and displayed rates are preserved. Use Refresh rates & review total before submitting.';}state=fresh;seen();render();if(focus){const el=root.querySelector('#'+CSS.escape(focus));el?.focus();if(el&&selection!==null&&['text','search'].includes(el.type))el.setSelectionRange(selection,selection);}return true;};
  async function save(path,body){
    if(root.busy)return;root.busy=true;root.querySelectorAll('button,input,textarea,select').forEach(el=>el.disabled=true);message='';
    try{state=await request(path,{method:'POST',body});seen();confirm=null;
      if(path==='/api/finance/deposits'){clearDraft(memberId);draft={quantities:{},notes:'',requestId:crypto.randomUUID()};history='pending';message='Deposit saved. Your outstanding balance and receipt are updated.';}
      else message='Saved. The updated records are shown below.';
      onClean();await onSaved();render();
    }catch(e){error(e);}finally{root.busy=false;root.querySelectorAll('button,input,textarea,select').forEach(el=>el.disabled=false);root.querySelectorAll('[data-finance-quantity]').forEach(i=>i.disabled=!state.bands.find(b=>b.id===i.dataset.financeQuantity)?.price);syncQuantityButtons();}
  }
  const identity=e=>[e.identity?.stateId?'State ID '+e.identity.stateId:'State ID not set',e.identity?.username?'@'+e.identity.username:''].filter(Boolean).join(' · ');
  const totalPaid=()=>state.payouts.filter(p=>p.userId===memberId&&!p.reversal).reduce((n,p)=>n+p.amount,0);
  function bandStrip(entries){const rows=stashBreakdown(entries);return rows.length?'<div class="band-strip">'+rows.map(b=>'<span style="--band:'+esc(b.color)+'"><i></i>'+esc(b.name)+' <strong>'+b.quantity.toLocaleString()+'</strong></span>').join('')+'</div>':'<p class="muted">No outstanding bands.</p>';}
  function entry(e,review=false){
    const payments=state.payouts.filter(p=>p.entryIds.includes(e.id)),partial=e.status==='pending'&&e.paidAmount>0;
    return '<article class="transaction-card" data-receipt-id="'+esc(e.id)+'"><details><summary><span><strong>'+esc(e.name)+'</strong><small>'+esc(timestamp(e.at))+' · '+esc(identity(e))+'</small></span><span><strong>'+money(e.remaining||depositTotal(e))+'</strong><small>'+({pending:partial?'Partially paid':e.requiresVerification&&!e.verified?'Awaiting verification':'Awaiting payout',paid:'Paid',rejected:'Rejected',withdrawn:'Withdrawn'}[e.status])+' <span aria-hidden="true">⌄</span></small></span></summary><div class="transaction-body">'+e.lines.map(l=>'<div class="finance-line"><span>'+esc(l.name)+' × '+l.quantity+' <small>at '+money(l.price)+'</small></span><strong>'+money(l.price*l.quantity)+'</strong></div>').join('')+
      (partial?'<p>Original value '+money(depositTotal(e))+' · Paid '+money(e.paidAmount)+' · Remaining '+money(e.remaining)+'</p>':'')+(e.notes?'<p>'+esc(e.notes)+'</p>':'')+
      (e.verified?'<p>Verified by '+esc(e.verified.byName)+' · '+esc(timestamp(e.verified.at))+'</p>':'')+
      payments.map(p=>'<p class="finance-receipt">'+(p.reversal?'Reversed payment':'Payment')+' '+money(p.allocations?.find(a=>a.entryId===e.id)?.amount??depositTotal(e))+' · '+esc(p.byName)+' · '+esc(timestamp(p.at))+'<br><small>Reference '+esc(p.id)+'</small>'+(p.reversal?'<br>Reversed by '+esc(p.reversal.byName)+': '+esc(p.reversal.reason):'')+(state.owner&&!p.reversal?'<button class="text-button" data-reverse="'+esc(p.id)+'" data-kind="payout">Correct this payment</button>':'')+'</p>').join('')+
      (e.reason?'<p class="finance-receipt">'+esc(e.reviewedByName)+' · '+esc(timestamp(e.reviewedAt))+'<br>'+esc(e.reason)+'</p>':'')+'<small class="record-reference">Deposit '+esc(e.id)+'</small></div></details><div class="entry-actions">'+
      (e.status==='pending'&&review&&state.canManage?(e.requiresVerification&&!e.verified?'<button class="button secondary" data-verify="'+esc(e.id)+'">Verify bands</button>':'')+(e.paidAmount?'':'<button class="text-button" data-reject="'+esc(e.id)+'">Reject incorrect deposit</button>'):'')+
      (e.userId===memberId&&e.status==='pending'&&!e.paidAmount?'<button class="text-button" data-withdraw="'+esc(e.id)+'">Withdraw / correct</button>':'')+
      (e.userId===memberId&&['withdrawn','rejected'].includes(e.status)?'<button class="text-button" data-copy="'+esc(e.id)+'">Use quantities in a new draft</button>':'')+'</div></article>';
  }
  function historyControls(){return '<details class="finance-filters" '+(filtersOpen||filter||statusFilter!=='all'||from||to?'open':'')+'><summary>Search & filter receipts</summary><div class="history-tools"><label>Search receipts<input data-history-search value="'+esc(filter)+'" placeholder="Name, State ID, reference…"></label><label>Status<select data-history-status>'+['all','pending','paid','rejected','withdrawn'].map(s=>'<option '+(s===statusFilter?'selected':'')+' value="'+s+'">'+({all:'All statuses',pending:'Unpaid',paid:'Paid',rejected:'Rejected',withdrawn:'Withdrawn'}[s])+'</option>').join('')+'</select></label><label>From<input type="date" data-history-from value="'+from+'"></label><label>To<input type="date" data-history-to value="'+to+'"></label><button type="button" class="text-button" data-clear-filters>Clear filters</button><button class="button secondary" data-export>Export CSV</button></div></details>';}
  function filtered(rows){return rows.filter(e=>(statusFilter==='all'||e.status===statusFilter)&&(!filter||[e.name,e.id,identity(e)].join(' ').toLowerCase().includes(filter.toLowerCase()))&&(!from||e.at.slice(0,10)>=from)&&(!to||e.at.slice(0,10)<=to));}
  function list(rows,review=false){const results=filtered(rows);return '<div data-transaction-results>'+results.slice(0,limit).map(e=>entry(e,review)).join('')+(results.length?'':'<div class="finance-empty">No matching records.</div>')+(results.length>limit?'<button class="button secondary" data-more>Load 20 more ('+(results.length-limit)+' remaining)</button>':'')+'</div>';}
  function ownPage(){
    const entries=own(),owed=outstanding(entries),pending=entries.filter(e=>e.status==='pending'),total=state.bands.reduce((n,b)=>n+b.price*(Number(draft.quantities[b.id])||0),0);
    const navigation='<nav class="tabs finance-nav" aria-label="My stash sections">'+[['add','Add bands'],['pending','Unpaid deposits'+(pending.length?' ('+pending.length+')':'')],['history','History']].map(([id,label])=>'<button data-own-tab="'+id+'" aria-pressed="'+(history===id)+'" class="'+(history===id?'selected':'')+'">'+label+'</button>').join('')+'</nav>';
    const form='<section class="panel finance-form-panel"><div class="finance-section-head"><div><h2>Add bands to your stash</h2><p>Enter the quantities you deposited. The value is calculated for you.</p></div></div><form id="finance-deposit-form"><div class="band-entry-heading"><span>Band / value each</span><span>Quantity</span></div><div class="band-entry-grid">'+state.bands.map(b=>'<div class="band-tile" style="--band:'+esc(b.color)+'"><span class="band-marker" aria-hidden="true"></span><label class="finance-band-name" for="finance-qty-'+esc(b.id)+'"><strong>'+esc(b.name)+'</strong><small>'+ (b.price?money(b.price)+' each':'Rate not set')+'</small></label><div class="quantity-stepper"><button type="button" data-quantity-step="-1" aria-label="Decrease '+esc(b.name)+' quantity">−</button><input id="finance-qty-'+esc(b.id)+'" aria-label="'+esc(b.name)+' quantity" data-finance-quantity="'+esc(b.id)+'" type="number" min="0" max="1000000" step="1" inputmode="numeric" value="'+esc(draft.quantities[b.id]||0)+'" '+(b.price?'':'disabled')+'><button type="button" data-quantity-step="1" aria-label="Increase '+esc(b.name)+' quantity">+</button></div></div>').join('')+'</div>'+
      '<label for="finance-note">Note (optional)</label><textarea id="finance-note" maxlength="2000" rows="2" placeholder="Where you left the bands…">'+esc(draft.notes)+'</textarea><div class="deposit-save-bar"><div><span>Deposit value</span><strong data-finance-total>'+money(total)+'</strong></div><button class="button primary">Save deposit</button></div><p class="draft-status" data-draft-status>'+(hasDraft()?'Draft saved on this device for 24 hours. Not submitted yet.':'Your draft saves on this device as you type.')+'</p><details class="finance-draft-options"><summary>Draft options</summary><div class="form-secondary-actions"><button type="button" class="text-button" data-refresh-rates>Refresh rates & review total</button><button type="button" class="text-button" data-discard>Discard draft</button></div></details></form></section>';
    const receipts='<section class="panel finance-history"><div class="finance-section-head"><div><h2>'+(history==='pending'?'Your unpaid deposits':'Your deposit history')+'</h2><p>'+(history==='pending'?'These deposits still have money owed to you.':'Paid, withdrawn, and rejected deposits. Open a receipt for details.')+'</p></div></div>'+(history==='pending'&&pending.length?'<details class="finance-band-summary"><summary>View unpaid band quantities</summary>'+bandStrip(pending)+(pending.some(e=>e.paidAmount)?'<p class="finance-help">Quantities are the original deposit contents. A partial payment reduces money owed, not band counts.</p>':'')+'</details>':'')+historyControls()+(entries.filter(e=>history==='pending'?e.status==='pending':e.status!=='pending').length?list(entries.filter(e=>history==='pending'?e.status==='pending':e.status!=='pending')):'<div data-transaction-results class="finance-empty"><h3>'+(history==='pending'?'Nothing owed right now.':'No past deposits yet.')+'</h3><p>'+(history==='pending'?'Save a deposit from Add bands to start tracking it.':'Completed and corrected deposits will appear here.')+'</p></div>')+'</section>';
    return '<div class="page-heading"><div><span class="eyebrow">YOUR FINANCES</span><h1>My stash</h1><p>Record your bands and see what you are owed.</p></div>'+(state.canViewLedger?'<button class="text-button" data-page="history">Go to treasury →</button>':'')+'</div>'+
      '<section class="stash-topline"><div><span>Owed to you</span><strong>'+money(owed)+'</strong></div><div><span>Already paid to you</span><strong>'+money(totalPaid())+'</strong></div><p>'+esc(state.user.name)+'<br>State ID '+esc(state.user.stateId||'not set')+'</p></section>'+navigation+
      '<div class="stash-workspace">'+(history==='add'?form+'<aside class="stash-guide"><h2>From stash to payment</h2><ol><li><strong>Save your deposit</strong><p>Record the bands you put in the stash.</p></li><li><strong>'+(state.requireVerification?'Staff verify your bands':'Your balance updates')+'</strong><p>'+(state.requireVerification?'A finance manager checks the quantities before payout.':'Your deposit is added to the amount owed to you.')+'</p></li><li><strong>Get paid in game</strong><p>Once staff record your payment, your balance updates and the receipt shows who paid you.</p></li></ol><p class="finance-help">Your amounts are visible to you and authorized finance staff.</p></aside>':receipts)+'</div>';
  }
  function ledgerPage(){
    const pending=state.deposits.filter(e=>e.status==='pending'),groups=[...new Set(pending.map(e=>e.userId))].map(id=>({id,entries:pending.filter(e=>e.userId===id)})),next=nextThursday(state.day),current=state.bills.filter(b=>b.dueDate===next),due=state.bills.filter(b=>b.status==='due'||b.status==='overdue'),remaining=state.bills.filter(b=>b.status!=='paid').reduce((n,b)=>n+b.amount,0),weekly=current.reduce((n,b)=>n+b.amount,0),paid=current.filter(b=>b.status==='paid').reduce((n,b)=>n+b.amount,0);
    let content='';
    if(tab==='payouts'){
      const visible=groups.filter(g=>!filter||[g.entries[0].name,identity(g.entries[0])].join(' ').toLowerCase().includes(filter.toLowerCase()));
      content='<section class="panel"><div class="finance-section-head"><div><h2>Pay members</h2><p>'+groups.length+' member'+(groups.length===1?' is':'s are')+' waiting for payment. Record payments after paying in game.</p></div></div><label class="queue-search">Find a member<input data-queue-search type="search" placeholder="Name or State ID…" value="'+esc(filter)+'"></label>'+visible.map(g=>{
        const e=g.entries[0],owed=outstanding(g.entries),unverified=g.entries.some(e=>e.requiresVerification&&!e.verified);
        return '<article class="payout-row"><div class="payout-overview"><div class="payout-identity"><span class="finance-avatar">'+esc(e.name.split(' ').map(n=>n[0]).slice(0,2).join(''))+'</span><div><h3>'+esc(e.name)+'</h3><small>'+esc(identity(e))+'</small><small>'+g.entries.length+' unpaid deposit'+(g.entries.length===1?'':'s')+(unverified?' · Verification needed':'')+'</small></div></div><div class="payout-amount"><span>Owed</span><strong>'+money(owed)+'</strong></div>'+(state.canManage?(g.id===memberId&&!session.user.owner?'<span class="payout-note">Another manager must record your payment.</span>':unverified?'<span class="payout-note">Verify the deposits below before payment.</span>':'<button class="button primary" data-pay="'+esc(g.id)+'">Record payment</button>'):'')+'</div><details class="payout-receipts"><summary>View deposits'+(unverified?' & verify bands':'')+'</summary>'+bandStrip(g.entries)+(g.entries.some(e=>e.paidAmount)?'<p class="finance-help">Quantities show original contents; the balance accounts for partial payments.</p>':'')+g.entries.map(e=>entry(e,true)).join('')+'</details></article>';
      }).join('')+(!visible.length?'<div class="finance-empty"><h3>'+(groups.length?'No matching members.':'All member payments are up to date.')+'</h3><p>'+(groups.length?'Try another name or State ID.':'New deposits will appear here when members save them.')+'</p></div>':'')+'</section>';
    }
    if(tab==='transactions')content='<section class="panel"><div class="finance-section-head"><div><h2>Deposit history</h2><p>All member deposits and their payment receipts. Open a record to see its details.</p></div></div>'+historyControls()+list(state.deposits,true)+'</section>';
    if(tab==='bills')content='<section class="panel"><h2>Weekly bills</h2><p>Gang house and gang taxes, due Thursdays in Central time. Tracking from '+esc(dayLabel(state.startDate))+'</p><div class="bill-progress"><span>Next Thursday · '+esc(dayLabel(next))+'<strong>'+money(weekly)+'</strong></span><span>Paid toward next Thursday <strong>'+money(paid)+'</strong></span><span>Still owed for next Thursday <strong>'+money(weekly-paid)+'</strong></span></div>'+state.bills.filter(b=>b.status!=='paid').map(b=>'<div class="finance-bill"><div><strong>'+esc(b.name)+'</strong><small>'+esc(dayLabel(b.dueDate))+' · '+esc(b.status)+'</small></div><strong>'+money(b.amount)+'</strong>'+(state.canManage?'<button class="button secondary" data-bill="'+esc(b.kind)+'" data-due="'+b.dueDate+'">Confirm paid</button>':'')+'</div>').join('')+'<details class="finance-bill-history"><summary>View past bill payments ('+state.billPayments.length+')</summary>'+(state.billPayments||[]).map(b=>'<div class="finance-bill"><div><strong>'+esc(b.kind==='house'?'Gang house':'Gang taxes')+' · '+money(b.amount)+'</strong><small>For '+esc(dayLabel(b.dueDate))+' · '+esc(b.byName)+' · '+esc(timestamp(b.at))+'</small>'+(b.reversal?'<small>Reversed: '+esc(b.reversal.reason)+'</small>':'')+'</div>'+(state.owner&&!b.reversal?'<button class="text-button" data-reverse="'+esc(b.id)+'" data-kind="bill">Correct payment</button>':'')+'</div>').join('')+'</details></section>';
    if(tab==='cash')content='<section class="panel"><h2>Gang cashbook</h2><p>Band submissions do not add cash. Record income when money is received. Confirmed payouts and bills subtract cash after the opening balance is set.</p>'+(state.cashEnabled?'<div class="bill-progress"><span>Cash recorded<strong>'+money(state.cashBalance)+'</strong></span><span>After bills & member balances<strong>'+money(state.cashBalance-remaining-outstanding(pending))+'</strong></span></div>':'<p class="notice">The Owner needs to enter the current cash balance to start tracking. Earlier payments will not be deducted again.</p>')+
      (state.canManage&&(state.cashEnabled||state.owner)?'<form id="cash-form" class="stack-form"><label>Entry type<select name="kind">'+(state.cashEnabled?'<option value="income">Cash received</option><option value="expense">Other expense</option>'+(state.owner?'<option value="reconcile">Reconcile to actual balance</option>':''):'<option value="opening">Opening cash balance</option>')+'</select></label><label>Amount<input name="amount" type="number" min="0" step="0.01" required></label><label>Reason / source<input name="reason" maxlength="500" required></label><button class="button primary">Review cash entry</button></form>':'')+
      '<h3 class="section-gap">Cash history</h3><button class="button secondary" data-cash-export>Export cash CSV</button>'+state.cashEntries.slice(0,limit).map(e=>'<div class="cash-row"><div><strong>'+esc(e.reason)+'</strong><small>'+esc(e.kind)+' · '+esc(e.byName)+' · '+esc(timestamp(e.at))+'</small>'+(e.reversal?'<small>Reversed: '+esc(e.reversal.reason)+'</small>':'')+'</div><strong>'+money(e.amount)+'</strong>'+(state.owner&&!e.reversal&&['income','expense','reconcile'].includes(e.kind)?'<button class="text-button" data-reverse="'+esc(e.id)+'" data-kind="cash">Correct</button>':'')+'</div>').join('')+(state.cashEntries.length>limit?'<button data-more class="button secondary">Load 20 more</button>':'')+'</section>';
    if(tab==='settings'&&state.owner)content='<section class="panel"><h2>Finance settings</h2><form id="finance-settings-form" class="stack-form"><label class="check-line"><input name="verification" type="checkbox" '+(state.requireVerification?'checked':'')+'> Require verification for new deposits</label><p>Existing deposits keep their original requirement. Verified bands still need a separate payment confirmation.</p><label>Tracking starts Thursday<input name="startDate" type="date" value="'+state.startDate+'" '+(state.deposits.length||state.billPayments.length?'disabled':'')+'></label><details><summary>Schedule a future weekly amount change ⌄</summary><label>Effective Thursday<input name="effectiveDate" type="date" min="'+next+'"></label><label>Gang house<input name="house" type="number" min="0" step="0.01" value="'+((current.find(b=>b.kind==='house')?.amount??500000)/100)+'"></label><label>Gang taxes<input name="taxes" type="number" min="0" step="0.01" value="'+((current.find(b=>b.kind==='taxes')?.amount??500000)/100)+'"></label></details><button class="button primary">Save finance settings</button></form><h3 class="section-gap">Scheduled amounts</h3>'+state.schedules.map(s=>'<p>From '+esc(dayLabel(s.effectiveDate))+': house '+money(s.house)+' + taxes '+money(s.taxes)+'</p>').join('')+
      '<div class="capacity-note">Workspace data: '+Math.round(state.capacity.bytes/1024)+' KB / '+Math.round(state.capacity.limit/1024)+' KB · '+state.capacity.deposits+' / '+state.capacity.recordLimit+' deposits. Complete capacity is also shown on the Owner home.</div></section>';
    return '<div class="page-heading"><div><span class="eyebrow">GANG FINANCES</span><h1>Treasury</h1><p>Pay members, keep bills current, and track gang cash.</p></div><div class="finance-heading-actions"><button class="text-button" data-page="overview">My stash →</button>'+(state.owner?'<button class="text-button" data-treasury-tab="settings" aria-pressed="'+(tab==='settings')+'">Finance settings</button>':'')+'</div></div><section class="treasury-metrics"><div><span>Owed to members</span><strong>'+money(outstanding(pending))+'</strong><small>'+groups.length+' member'+(groups.length===1?'':'s')+' awaiting payment</small></div><div><span>Bills due now</span><strong>'+money(due.reduce((n,b)=>n+b.amount,0))+'</strong><small>'+(due.length?due.length+' unpaid bill'+(due.length===1?'':'s'):'No due or overdue bills')+'</small></div><div><span>Gang cash on hand</span><strong>'+(state.cashEnabled?money(state.cashBalance):'Not set up')+'</strong><small>'+(state.cashEnabled?'Recorded in the gang cashbook':'Optional · set up in Gang cash')+'</small></div></section><nav class="tabs treasury-tabs finance-nav" aria-label="Treasury sections">'+[['payouts','Pay members'],['bills','Weekly bills'],['transactions','Deposit history'],['cash','Gang cash']].map(([id,label])=>'<button data-treasury-tab="'+id+'" aria-pressed="'+(tab===id)+'" class="'+(tab===id?'selected':'')+'">'+label+'</button>').join('')+'</nav>'+content;
  }
  function confirmation(){
    if(!confirm)return '';const c=confirm;
    return '<section class="finance-confirm panel" aria-label="Review finance action"><h2>'+esc(c.title)+'</h2><p>'+esc(c.description)+'</p><form id="finance-confirm-form">'+(c.amount?'<label>Payment amount<input name="amount" type="number" min="0.01" step="0.01" max="'+c.amount/100+'" value="'+c.amount/100+'" required></label><p>You may pay part of the balance. Payments apply to the oldest outstanding deposits first.</p>':'')+(c.reason?'<label>Reason<textarea name="reason" required maxlength="500"></textarea></label>':'')+'<p>'+esc(c.note||'This records an action taken in game. Review before confirming.')+'</p><div class="finance-confirm-actions"><button class="button primary">Confirm '+esc(c.verb||'change')+'</button><button type="button" class="button secondary" data-cancel>Cancel</button><button type="button" class="text-button" data-refresh-confirm>Refresh current records</button></div></form></section>';
  }
  function showConfirm(c){confirm=c;root.querySelector('[data-finance-confirm]').innerHTML=confirmation();bindConfirm();root.querySelector('[data-finance-confirm]').scrollIntoView({block:'nearest'});root.querySelector('#finance-confirm-form input,#finance-confirm-form textarea,#finance-confirm-form button')?.focus();}
  function bindConfirm(){
    root.querySelector('[data-cancel]')?.addEventListener('click',()=>{confirm=null;onClean();render();});
    root.querySelector('[data-refresh-confirm]')?.addEventListener('click',async()=>{confirm=null;onClean();try{state=await request('/api/finance');seen();message='Records refreshed. Select the action again to review the current amounts.';render();}catch(e){error(e);}});
    root.querySelector('#finance-confirm-form')?.addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget,c=confirm;save(c.path,{...c.body,...(c.amount?{amount:Math.round(Number(form.elements.amount.value)*100)}:{}),...(c.reason?{reason:form.elements.reason.value}:{})});});
  }
  function render(){if(!root.isConnected)return;root.innerHTML='<div class="notice" data-finance-message role="status" '+(message?'':'hidden')+'>'+esc(message)+'</div><div data-finance-confirm>'+confirmation()+'</div>'+(mode==='bands'?ownPage():ledgerPage());bind();bindConfirm();}
  function refreshList(){const rows=mode==='bands'?own().filter(e=>history==='pending'?e.status==='pending':e.status!=='pending'):state.deposits;root.querySelector('[data-transaction-results]').outerHTML=list(rows,mode!=='bands');bindEntries();}
  function bindEntries(){
    root.querySelectorAll('[data-reverse]').forEach(b=>b.onclick=()=>showConfirm({title:'Correct recorded '+b.dataset.kind,description:'The original record remains in history. A reversal restores the outstanding amount and adjusts linked cash entries.',reason:true,path:'/api/finance/reversals',body:{requestId:crypto.randomUUID(),recordId:b.dataset.reverse,kind:b.dataset.kind,revision:state.revision},verb:'reversal'}));
    for(const [attr,decision,title] of [['data-withdraw','withdraw','Withdraw this deposit'],['data-reject','reject','Reject this deposit'],['data-verify','verify','Verify received bands']])root.querySelectorAll('['+attr+']').forEach(b=>b.onclick=()=>{const e=state.deposits.find(e=>e.id===b.getAttribute(attr));showConfirm({title,description:e.name+' · '+money(depositTotal(e)),reason:decision!=='verify',path:'/api/finance/deposits/'+e.id,body:{decision},verb:decision,note:decision==='verify'?'Confirm you have checked the quantities. This does not record a payment.':'The original deposit and reason remain in history.'});});
    root.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>{if(hasDraft()){error(Error('Discard or save your current draft before copying another deposit.'));return;}const e=state.deposits.find(e=>e.id===b.dataset.copy);draft={quantities:Object.fromEntries(e.lines.filter(l=>state.bands.some(b=>b.id===l.id)).map(l=>[l.id,l.quantity])),notes:e.notes,requestId:crypto.randomUUID()};history='add';saveDraft(memberId,draft);message='Quantities copied into a new draft at current rates. Review before submitting.';render();root.querySelector('#finance-deposit-form')?.scrollIntoView({block:'start'});});
    root.querySelectorAll('[data-more]').forEach(b=>b.onclick=()=>{limit+=20;tab==='cash'?render():refreshList();});
  }
  function syncQuantityButtons(){
    root.querySelectorAll('[data-quantity-step]').forEach(button=>{
      const input=button.closest('.quantity-stepper').querySelector('input'),value=Number(input.value)||0;
      button.disabled=root.busy||input.disabled||(Number(button.dataset.quantityStep)<0?value<=Number(input.min):value>=Number(input.max));
    });
  }
  function bind(){
    const form=root.querySelector('#finance-deposit-form');
    syncQuantityButtons();
    form?.addEventListener('input',syncQuantityButtons);
    root.querySelectorAll('[data-quantity-step]').forEach(button=>button.addEventListener('click',()=>{
      const input=button.closest('.quantity-stepper').querySelector('input');
      if(input.disabled||root.busy)return;
      if(!input.value||!Number.isFinite(Number(input.value)))input.value='0';
      Number(button.dataset.quantityStep)>0?input.stepUp():input.stepDown();
      input.dispatchEvent(new Event('input',{bubbles:true}));
    }));
    form?.addEventListener('input',()=>{draft.quantities=Object.fromEntries([...form.querySelectorAll('[data-finance-quantity]')].map(i=>[i.dataset.financeQuantity,i.value]));draft.notes=form.querySelector('#finance-note').value;draftStored=saveDraft(memberId,draft);root.querySelector('[data-draft-status]').textContent=draftStored?'Draft — not submitted. Saved on this device for 24 hours.':'Draft is in this tab only. Device storage is unavailable.';root.querySelector('[data-finance-total]').textContent=money(state.bands.reduce((n,b)=>n+b.price*(Number(draft.quantities[b.id])||0),0));onClean();});
    form?.addEventListener('submit',e=>{e.preventDefault();const lines=state.bands.filter(b=>Number(draft.quantities[b.id])>0).map(b=>({id:b.id,quantity:Number(draft.quantities[b.id])}));if(!lines.length){error(Error('Enter at least one band quantity.'));return;}save('/api/finance/deposits',{requestId:draft.requestId,ratesVersion:state.ratesVersion,lines,notes:draft.notes});});
    root.querySelector('[data-discard]')?.addEventListener('click',()=>{clearDraft(memberId);draft={quantities:{},notes:'',requestId:crypto.randomUUID()};onClean();message='Draft discarded.';render();});
    root.querySelector('[data-refresh-rates]')?.addEventListener('click',async()=>{try{const before=state.bands.reduce((n,b)=>n+b.price*(Number(draft.quantities[b.id])||0),0);state=await request('/api/finance');seen();draft.quantities=Object.fromEntries(Object.entries(draft.quantities).filter(([id])=>state.bands.some(b=>b.id===id&&b.price)));saveDraft(memberId,draft);onClean();const after=state.bands.reduce((n,b)=>n+b.price*(Number(draft.quantities[b.id])||0),0);message='Rates refreshed: '+money(before)+' → '+money(after)+'. Quantities for unavailable bands were removed. Review and save when ready.';render();}catch(e){error(e);}});
    root.querySelectorAll('[data-own-tab]').forEach(b=>b.onclick=()=>{history=b.dataset.ownTab;filter='';statusFilter='all';from='';to='';filtersOpen=false;limit=20;confirm=null;render();root.querySelector('[data-own-tab="'+history+'"]')?.focus();});
    root.querySelectorAll('[data-treasury-tab]').forEach(b=>b.onclick=()=>{if(!canRefresh()&&!confirm){error(Error('Save or discard the form before switching sections.'));return;}tab=b.dataset.treasuryTab;filter='';statusFilter='all';from='';to='';filtersOpen=false;limit=20;confirm=null;onClean();render();root.querySelector('[data-treasury-tab="'+tab+'"]')?.focus();});
    root.querySelector('.finance-filters')?.addEventListener('toggle',e=>{if(e.currentTarget.isConnected)filtersOpen=e.currentTarget.open;});
    root.querySelector('[data-clear-filters]')?.addEventListener('click',()=>{filter='';statusFilter='all';from='';to='';limit=20;filtersOpen=true;render();root.querySelector('[data-history-search]')?.focus();});
    for(const [key,set] of [['search',v=>filter=v],['status',v=>statusFilter=v],['from',v=>from=v],['to',v=>to=v]])root.querySelector('[data-history-'+key+']')?.addEventListener(key==='search'?'input':'change',e=>{set(e.target.value);limit=20;refreshList();});
    root.querySelector('[data-queue-search]')?.addEventListener('input',e=>{filter=e.target.value;const pos=e.target.selectionStart;render();const input=root.querySelector('[data-queue-search]');input.focus();input.setSelectionRange(pos,pos);});
    root.querySelector('[data-cash-export]')?.addEventListener('click',()=>downloadCsv('pto-cashbook-'+state.day+'.csv',[['Reference','Date','Type','Amount','Recorded by','Reason','Reversed'],...state.cashEntries.map(e=>[e.id,e.at,e.kind,e.amount/100,e.byName,e.reason,e.reversal?'Yes':'No'])]));
    root.querySelector('[data-export]')?.addEventListener('click',()=>{const rows=filtered(mode==='bands'?own().filter(e=>history==='pending'?e.status==='pending':e.status!=='pending'):state.deposits);downloadCsv('pto-transactions-'+state.day+'.csv',[['Reference','Member','State ID','Submitted','Status','Original value','Paid','Remaining','Note','Review reason'],...rows.map(e=>[e.id,e.name,e.identity?.stateId,e.at,e.status,depositTotal(e)/100,e.paidAmount/100,e.remaining/100,e.notes,e.reason])]);});
    root.querySelectorAll('[data-pay]').forEach(b=>b.onclick=()=>{const entries=state.deposits.filter(e=>e.userId===b.dataset.pay&&e.status==='pending'),owed=outstanding(entries);showConfirm({title:'Record member payment',description:entries[0].name+' · '+identity(entries[0])+(entries[0].identity?.phone?' · Phone '+entries[0].identity.phone:'')+' · '+money(owed)+' outstanding',amount:owed,path:'/api/finance/payouts',body:{requestId:crypto.randomUUID(),userId:b.dataset.pay,expectedOutstanding:owed,expectedEntryIds:entries.map(e=>e.id)},verb:'payment'});});
    root.querySelectorAll('[data-bill]').forEach(b=>b.onclick=()=>{const bill=state.bills.find(x=>x.kind===b.dataset.bill&&x.dueDate===b.dataset.due);showConfirm({title:'Confirm weekly payment',description:bill.name+' · '+money(bill.amount)+' · due '+dayLabel(bill.dueDate),path:'/api/finance/bills',body:{requestId:crypto.randomUUID(),kind:bill.kind,dueDate:bill.dueDate,expectedAmount:bill.amount},verb:'payment'});});
    root.querySelector('#cash-form')?.addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;showConfirm({title:'Review cashbook entry',description:f.elements.kind.value+' · '+money(Math.round(Number(f.elements.amount.value)*100))+' · '+f.elements.reason.value,path:'/api/finance/cash',body:{requestId:crypto.randomUUID(),revision:state.revision,kind:f.elements.kind.value,amount:Math.round(Number(f.elements.amount.value)*100),reason:f.elements.reason.value},verb:'cash entry'});});
    root.querySelector('#finance-settings-form')?.addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;save('/api/finance/settings',{revision:state.revision,requireVerification:f.elements.verification.checked,startDate:f.elements.startDate.value,...(f.elements.effectiveDate.value?{schedule:{effectiveDate:f.elements.effectiveDate.value,house:Math.round(Number(f.elements.house.value)*100),taxes:Math.round(Number(f.elements.taxes.value)*100)}}:{})});});
    bindEntries();
  }
  try{state=await request('/api/finance');if(!root.isConnected)return;seen();render();}catch(e){root.innerHTML='<p class="notice error">'+esc(e.message)+'</p>';}
}
