import {escapeHtml as esc,timestamp,dayLabel} from './ui-utils.js';
import {permits} from './access-model.js';
import {outstanding,financeMoney as money} from './finance-model.js';
export async function mountHub(root,session,{request,canRefresh,onClean}){
  let state,finance,notice='',editing=null,busy=false;const mode=root.dataset.hubMode;
  root.seenAccounts=session.versions?.accounts;root.seenRequests=session.versions?.requests;
  const formKey=f=>f.id||f.dataset.rsvp||f.dataset.attendance;
  const savedForm=path=>({'/api/hub/events':'event-form','/api/hub/availability':'availability-form','/api/hub/notes':'leadership-form'}[path]);
  const preserveForms=(path,body)=>[...root.querySelectorAll('form[data-edited]')].filter(f=>formKey(f)!==savedForm(path)&&formKey(f)!==body.id).map(f=>({key:formKey(f),values:[...f.elements].filter(el=>el.name).map(el=>({name:el.name,value:el.value})),editing:f.id==='event-form'?editing:null}));
  function restoreForms(drafts){for(const d of drafts){const f=[...root.querySelectorAll('form')].find(f=>formKey(f)===d.key);if(!f)continue;for(const v of d.values)if(f.elements[v.name])f.elements[v.name].value=v.value;f.dataset.edited='true';f.dispatchEvent(new Event('input',{bubbles:true}));}}
  root.addEventListener('input',e=>{const f=e.target.closest('form');if(f)f.dataset.edited='true';});root.addEventListener('change',e=>{const f=e.target.closest('form');if(f)f.dataset.edited='true';});
  Object.defineProperty(root,'busy',{get:()=>busy});
  async function load(preserve=false){const h=await request('/api/hub');let f;if(mode==='home'&&(permits(session.permissions,'bands')||permits(session.permissions,'ledger')))f=await request('/api/finance');if(!root.isConnected||preserve&&!canRefresh())return false;state=h;finance=f;root.seenRevision=h.revision;render();return true;}
  root.refreshFromServer=async()=>{if(busy||!canRefresh())return false;return await load(true);};
  async function save(path,body){if(busy)return;const drafts=preserveForms(path,body);busy=true;root.querySelectorAll('button,input,textarea,select').forEach(b=>b.disabled=true);try{state=await request(path,{method:'POST',body:{revision:state.revision,...body}});notice='Saved. Everyone with access will see the update.';editing=drafts.find(d=>d.key==='event-form')?.editing||null;onClean();root.seenRevision=state.revision;render();restoreForms(drafts);}catch(e){notice=e.message;const n=root.querySelector('[data-hub-notice]');if(n){n.hidden=false;n.textContent=notice;}}finally{busy=false;root.querySelectorAll('button,input,textarea,select').forEach(b=>b.disabled=false);}}
  const announcements=()=>'<section class="panel"><div class="finance-section-head"><h2>Updates for you</h2><button class="text-button" data-read-all>Mark all read</button></div>'+state.notifications.map(n=>'<article class="notification-row '+(n.read?'read':'')+'"><div><strong>'+esc(n.title)+'</strong><small>'+esc(timestamp(n.at))+'</small></div><button class="button secondary" data-notification="'+esc(n.id)+'" data-destination="'+esc(n.page)+'" data-receipt="'+esc(n.recordId||'')+'">Open</button></article>').join('')+(!state.notifications.length?'<p>You’re all caught up.</p>':'')+'</section>';
  function home(){
    const owner=state.owner,own=finance?.deposits.filter(e=>e.userId===session.user.id)||[],bills=finance?.bills.filter(b=>b.status!=='paid')||[];
    return '<div class="page-heading"><div><span class="eyebrow">PTO / WORKSPACE</span><h1>'+esc(session.user.name)+'</h1><p>Your gang, organized for today.</p></div></div><div class="home-metrics">'+(owner?'<button data-page="requests"><span>Join requests</span><strong>'+owner.pending+'</strong></button><button data-page="access"><span>Profiles to complete</span><strong>'+owner.incomplete.length+'</strong></button>':'')+(finance?'<button data-page="overview"><span>Owed to you</span><strong>'+money(outstanding(own))+'</strong></button>':'')+(permits(session.permissions,'ledger')?'<button data-page="history"><span>Gang payouts waiting</span><strong>'+money(outstanding(finance?.deposits||[]))+'</strong></button><button data-page="history"><span>Outstanding weekly bills</span><strong>'+money(bills.reduce((n,b)=>n+b.amount,0))+'</strong></button>':'')+'</div><div class="home-grid"><section class="panel"><h2>Quick actions</h2><div class="quick-actions">'+(permits(session.permissions,'bands')?'<button class="button primary" data-page="overview">Record my bands</button>':'')+(state.canSeeRoster?'<button class="button secondary" data-page="events">Calendar & availability</button><button class="button secondary" data-page="roster">Open roster</button>':'')+'</div><h3 class="section-gap">Next events</h3>'+state.events.filter(e=>!e.cancelled&&Date.parse(e.at)>=Date.now()).sort((a,b)=>a.at.localeCompare(b.at)).slice(0,3).map(e=>'<p><strong>'+esc(e.title)+'</strong><br>'+esc(timestamp(e.at))+'</p>').join('')+(state.events.some(e=>!e.cancelled&&Date.parse(e.at)>=Date.now())?'':'<p>No upcoming events.</p>')+'</section>'+announcements()+'</div>'+
      (owner?'<section class="panel section-gap"><h2>Owner overview</h2><p>'+owner.administrators.length+' other account'+(owner.administrators.length===1?'':'s')+' with full account administration. Review effective access in People & roles.</p>'+(owner.incomplete.length?'<p>Missing profile details: '+owner.incomplete.map(u=>esc(u.name)).join(', ')+'</p>':'<p>All approved profiles have a State ID and phone.</p>')+'<p>Workspace and identity data estimate: '+Math.round(owner.bytes/1024)+' KB / '+Math.round(owner.limit/1024)+' KB. Capacity includes additional server security state; this estimate is a lower bound.</p><div class="quick-actions"><button class="button secondary" data-page="access">Manage people</button><button class="button secondary" data-owner-backups>Full backups</button><button class="button secondary" data-action="account">Account security & recovery</button></div></section>':'');
  }
  function events(){
    const e=editing,local=e?new Date(Date.parse(e.at)-new Date(e.at).getTimezoneOffset()*60000).toISOString().slice(0,16):'',availability=state.availability.find(a=>a.userId===session.user.id);
    return '<div class="page-heading"><div><span class="eyebrow">PTO / TOGETHER</span><h1>Calendar & availability</h1><p>Plan meetings, respond, and let the gang know when you’re away.</p></div></div><div class="home-grid"><section class="panel"><h2>Gang calendar</h2>'+state.events.slice().sort((a,b)=>a.at.localeCompare(b.at)).map(e=>'<article class="event-card"><span class="event-date">'+esc(new Date(e.at).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}))+'</span><h3>'+esc(e.title)+(e.cancelled?' · Cancelled':'')+'</h3><p>'+esc(timestamp(e.at))+' · '+esc(e.location||'Location to be confirmed')+'</p><p>'+esc(e.notes)+'</p>'+(!e.cancelled?'<form data-rsvp="'+esc(e.id)+'" class="inline-form"><label>Your response<select name="response">'+[['yes','Going'],['maybe','Maybe'],['no','Not going']].map(([v,l])=>'<option value="'+v+'" '+(e.responses.find(r=>r.userId===session.user.id)?.response===v?'selected':'')+'>'+l+'</option>').join('')+'</select></label><button class="button secondary">Save response</button></form>':'')+'<details><summary>Responses & attendance ('+e.responses.length+') ⌄</summary>'+e.responses.map(r=>'<p>'+esc(r.name)+' · '+esc(r.response)+'</p>').join('')+(state.canManage&&!e.cancelled?'<form data-attendance="'+esc(e.id)+'" class="stack-form"><label>Member<select name="userId">'+state.members.filter(m=>m.userId).map(m=>'<option value="'+esc(m.userId)+'">'+esc(m.name)+'</option>').join('')+'</select></label><label>Attendance<select name="response"><option value="attended">Attended</option><option value="absent">Absent</option></select></label><button class="button secondary">Record attendance</button></form>':'')+'</details>'+(state.canManage&&!e.cancelled?'<div class="entry-actions"><button class="text-button" data-edit-event="'+esc(e.id)+'">Edit event</button><button class="text-button" data-cancel-event="'+esc(e.id)+'">Cancel event</button></div>':'')+'</article>').join('')+(!state.events.length?'<p>No meetings planned yet.</p>':'')+'</section><div>'+
      (state.canManage?'<section class="panel"><h2>'+ (e?'Edit event':'Plan an event')+'</h2><form id="event-form" class="stack-form"><label>Title<input name="title" maxlength="100" value="'+esc(e?.title||'')+'" required></label><label>Date & time (your local time)<input name="at" type="datetime-local" value="'+local+'" required></label><label>Location<input name="location" maxlength="200" value="'+esc(e?.location||'')+'"></label><label>Details<textarea name="notes" maxlength="2000">'+esc(e?.notes||'')+'</textarea></label><button class="button primary">Save event</button><button type="button" class="text-button" data-discard-event>Discard edits</button></form></section>':'')+
      '<section class="panel section-gap"><h2>Your availability</h2><form id="availability-form" class="stack-form"><label>Away from<input name="from" type="date" value="'+esc(availability?.from||'')+'" required></label><label>Through<input name="to" type="date" value="'+esc(availability?.to||'')+'" required></label><label>Shared note<input name="note" maxlength="500" value="'+esc(availability?.note||'')+'"></label><button class="button primary">Save away dates</button><button type="button" class="text-button" data-clear-away>Clear away dates</button></form><h3 class="section-gap">Gang availability</h3>'+state.availability.filter(a=>a.to>=state.day).map(a=>'<p><strong>'+esc(a.name)+'</strong><br>'+esc(dayLabel(a.from))+' – '+esc(dayLabel(a.to))+'<br>'+esc(a.note)+'</p>').join('')+'</section>'+
      (state.canManage?'<section class="panel section-gap"><h2>Leadership notes</h2><p>Visible only to people who can manage the roster.</p><form id="leadership-form" class="stack-form"><label>Roster member<select name="memberId">'+state.members.map(m=>'<option value="'+esc(m.id)+'">'+esc(m.name)+'</option>').join('')+'</select></label><label>Private note<textarea name="note" maxlength="2000">'+esc(state.notes[state.members[0]?.id]||'')+'</textarea></label><button class="button primary" '+(!state.members.length?'disabled':'')+'>Save private note</button></form></section>':'')+'</div></div>';
  }
  function render(){
    if(!root.isConnected)return;root.innerHTML='<div class="notice" data-hub-notice role="status" '+(notice?'':'hidden')+'>'+esc(notice)+'</div>'+(mode==='home'?home():mode==='notifications'?'<div class="page-heading"><h1>Your updates</h1></div>'+announcements():events());
    const unread=state.notifications.filter(n=>!n.read).length;document.querySelectorAll('[data-unread-count]').forEach(n=>{n.textContent=unread;n.hidden=!unread;});
    root.querySelector('[data-read-all]')?.addEventListener('click',()=>save('/api/hub/read',{ids:state.notifications.map(n=>n.id)}));
    root.querySelectorAll('[data-notification]').forEach(b=>b.onclick=async()=>{await save('/api/hub/read',{ids:[b.dataset.notification]});document.dispatchEvent(new CustomEvent('pto:navigate',{detail:{page:b.dataset.destination,receipt:b.dataset.receipt}}));});
    root.querySelector('[data-owner-backups]')?.addEventListener('click',()=>{document.dispatchEvent(new CustomEvent('pto:navigate',{detail:'access'}));document.dispatchEvent(new CustomEvent('pto:access-tab',{detail:'backups'}));});
    root.querySelectorAll('[data-rsvp],[data-attendance]').forEach(f=>f.onsubmit=e=>{e.preventDefault();save('/api/hub/rsvp',{id:f.dataset.rsvp||f.dataset.attendance,response:f.elements.response.value,...(f.elements.userId?{userId:f.elements.userId.value}:{})});});
    root.querySelector('#event-form')?.addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;save('/api/hub/events',{id:editing?.id||crypto.randomUUID(),title:f.elements.title.value,at:new Date(f.elements.at.value).toISOString(),location:f.elements.location.value,notes:f.elements.notes.value});});
    root.querySelectorAll('[data-edit-event]').forEach(b=>b.onclick=()=>{if(!canRefresh()&&!window.confirm('Discard unsaved calendar edits and open this event?'))return;onClean();editing=state.events.find(e=>e.id===b.dataset.editEvent);render();root.querySelector('#event-form').scrollIntoView({block:'start'});});
    root.querySelectorAll('[data-cancel-event]').forEach(b=>b.onclick=()=>{if(window.confirm('Cancel this event? Its history and responses will remain.'))save('/api/hub/events',{id:b.dataset.cancelEvent,cancel:true});});
    root.querySelector('[data-discard-event]')?.addEventListener('click',()=>{editing=null;onClean();render();});
    root.querySelector('#availability-form')?.addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;save('/api/hub/availability',{from:f.elements.from.value,to:f.elements.to.value,note:f.elements.note.value});});
    root.querySelector('[data-clear-away]')?.addEventListener('click',()=>save('/api/hub/availability',{clear:true}));
    root.querySelector('#leadership-form')?.addEventListener('change',e=>{if(e.target.name==='memberId'){const f=e.currentTarget;if(f.dataset.noteEdited&&!window.confirm('Discard the unsaved private note and select another member?')){e.target.value=f.dataset.noteMember;return;}f.elements.note.value=state.notes[e.target.value]||'';delete f.dataset.noteEdited;f.dataset.noteMember=e.target.value;}});
    root.querySelector('#leadership-form textarea')?.addEventListener('input',e=>{const f=e.target.form;f.dataset.noteEdited='true';f.dataset.noteMember=f.elements.memberId.value;});
    root.querySelector('#leadership-form')?.addEventListener('submit',e=>{e.preventDefault();save('/api/hub/notes',{memberId:e.currentTarget.elements.memberId.value,note:e.currentTarget.elements.note.value});});
  }
  try{await load();}catch(e){root.innerHTML='<p class="notice error">'+esc(e.message)+'</p>';}
}
