import { rosterCounts, balance } from './model.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials=name=>name.trim().split(/\s+/).slice(0,2).map(n=>n[0]).join('').toUpperCase();
const money=value=>'$'+(value/100).toLocaleString('en-US',{maximumFractionDigits:2});
export function rosterRows(data,query='',filter='current') {
  const members=data.members.filter(m=>(filter==='current'?m.status!=='archived':m.status===filter)&&`${m.name} ${m.rank} ${m.callsign} ${m.notes}`.toLowerCase().includes(query.toLowerCase()))
    .sort((a,b)=>(data.ranks.indexOf(a.rank)<0?999:data.ranks.indexOf(a.rank))-(data.ranks.indexOf(b.rank)<0?999:data.ranks.indexOf(b.rank))||a.name.localeCompare(b.name));
  return members.length?`<div class="roster-columns" aria-hidden="true"><span>MEMBER</span><span>RANK</span><span>STATUS</span><span></span></div>${members.map(m=>`<button class="roster-row" data-edit-member="${esc(m.id)}" aria-label="View ${esc(m.name)}"><span class="member-identity"><span class="member-avatar">${esc(initials(m.name))}</span><span><strong>${esc(m.name)}</strong><small>${esc(m.callsign||'No callsign')}</small></span></span><span class="rank-tag rank-tone-${Math.max(0,data.ranks.indexOf(m.rank))%4}">${esc(m.rank)}</span><span class="member-status ${m.status}"><i></i>${m.status==='active'?'Active':m.status==='inactive'?'Inactive':'Archived'}</span><span class="row-arrow" aria-hidden="true">↗</span></button>`).join('')}`:`<div class="empty roster-empty"><h3>${query?'No matching members.':filter==='archived'?'No archived members.':filter==='active'?'No active members.':filter==='inactive'?'No inactive members.':'Your roster starts here.'}</h3><p>${query?'Try a different name, rank, or callsign.':filter==='archived'?'Members you archive stay available here.':filter!=='current'?'Choose All to see the rest of your roster.':'Add your first member to keep names, ranks, and status together.'}</p>${!query&&filter==='current'?'<button class="button primary" data-action="add-member">+ Add member</button>':query||filter!=='current'?'<button class="button secondary" data-action="reset-roster">Show all members</button>':''}</div>`;
}
export function rosterPage(data,query='',filter='current') {
  const counts=rosterCounts(data.members,data.rosterLimit),owed=data.purchases.reduce((sum,p)=>sum+balance(p),0);
  return `<div class="page-heading"><div><div class="roster-kicker">PTO / MEMBERS</div><h1>Gang roster</h1><p>Your people, their ranks, and where everyone stands.</p></div><div class="heading-actions"><button class="button primary" data-action="add-member">+ Add member</button></div></div>
  <section class="roster-summary" aria-label="Roster totals"><div class="roster-size"><span>ON THE ROSTER</span><strong>${counts.total}${data.rosterLimit?`<small> / ${data.rosterLimit}</small>`:''}</strong><p>${data.rosterLimit?`${counts.open} open ${counts.open===1?'spot':'spots'}${counts.total>data.rosterLimit?' · Above roster limit':''}`:'No roster limit set'}</p></div><div class="roster-count"><span class="member-status active"><i></i>Active</span><strong>${counts.active}</strong></div><div class="roster-count"><span class="member-status inactive"><i></i>Inactive</span><strong>${counts.inactive}</strong></div><div class="roster-explainer">Keep the roster current.<small>Status is updated manually.</small><button class="text-button" data-page="settings">Ranks & roster settings →</button></div></section>
  <div class="gang-grid"><section class="panel roster-panel"><div class="roster-toolbar"><div class="tabs" aria-label="Filter members">${[['current','All',counts.total],['active','Active',counts.active],['inactive','Inactive',counts.inactive],['archived','Archive',counts.archived]].map(([id,label,count])=>`<button data-member-filter="${id}" class="${filter===id?'selected':''}" aria-pressed="${filter===id}">${label}<span>${count}</span></button>`).join('')}</div><label class="search-field"><input id="roster-search" placeholder="Search name, rank, callsign…" aria-label="Search roster" value="${esc(query)}"></label></div><div id="roster-results">${rosterRows(data,query,filter)}</div></section>
  <aside class="gang-sidebar"><section class="panel gang-notes"><div class="panel-header"><h2>Gang notes</h2><button class="text-button" data-action="gang-notes">Edit</button></div><p class="notes-body">${esc(data.gangNotes||'A place for meeting reminders, priorities, and anything the gang needs to know.')}</p></section><section class="panel gang-bands"><div class="panel-header"><h2>Band ledger</h2></div><span class="muted">Total owed to players</span><strong>${money(owed)}</strong><button class="button secondary" data-page="overview">Record bands →</button><button class="text-button" data-page="history">View ledger</button></section></aside></div>`;
}
export function memberForm(data,member) {
  const today=new Date().toLocaleDateString('en-CA');
  return `<h2>${member?'Edit member':'Add member'}</h2><p class="member-form-intro">Keep their in-game details in one place.</p><form id="member-form" class="member-form"><div class="member-fields"><div><label for="member-name">In-game name</label><input id="member-name" required maxlength="60" value="${esc(member?.name||'')}" autofocus></div><div><label for="member-callsign">Callsign <span class="muted">(optional)</span></label><input id="member-callsign" maxlength="40" placeholder="Callsign" value="${esc(member?.callsign||'')}"></div></div><label for="member-rank-search">Rank</label><div class="player-picker" id="member-rank-picker"><input type="hidden" id="member-rank"><div class="picker-control"><input id="member-rank-search" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="member-rank-options" aria-haspopup="listbox" autocomplete="off" required><button type="button" class="picker-toggle" data-picker-toggle aria-label="Open rank list" tabindex="-1">⌄</button></div><div class="picker-panel" data-picker-panel hidden><div id="member-rank-options" role="listbox" aria-label="Ranks"></div><p class="picker-message" data-picker-message hidden></p></div></div><fieldset class="status-choices"><legend>Status</legend>${['active','inactive',...(member?.status==='archived'?['archived']:[])].map(status=>`<label><input type="radio" name="member-status" value="${status}" ${(member?.status||'active')===status?'checked':''}>${status[0].toUpperCase()+status.slice(1)}</label>`).join('')}</fieldset><label for="member-joined">Date joined</label><input type="date" id="member-joined" required value="${esc(member?.joined||today)}"><label for="member-notes">Notes <span class="muted">(optional)</span></label><textarea id="member-notes" rows="3" maxlength="2000" placeholder="Availability, responsibilities, or reminders…">${esc(member?.notes||'')}</textarea><div class="form-error" id="member-error" role="alert"></div><div class="member-actions"><button type="submit" class="button primary">${member?'Save member':'Add member'}</button>${member&&member.status!=='archived'?`<button type="button" class="text-button" data-archive-member="${esc(member.id)}">Move to archive</button>`:''}</div></form>`;
}
export function gangSettings(data) {
  return `<form id="gang-settings-form" class="gang-settings panel settings-panel"><h2>Gang settings</h2><p>Make the roster fit your gang.</p><label for="gang-name">Website name</label><input id="gang-name" required maxlength="40" value="${esc(data.name)}"><label for="roster-limit">Roster limit</label><input id="roster-limit" type="number" min="0" max="2000" step="1" value="${data.rosterLimit}" required><small>Use 0 for no limit. Archived members do not count.</small><label for="gang-ranks">Ranks, highest first</label><textarea id="gang-ranks" rows="5" required maxlength="1230">${esc(data.ranks.join('\n'))}</textarea><small>One rank per line. Members keep their current rank if you remove it here.</small><div class="form-error" id="gang-settings-error" role="alert"></div><button class="button primary" type="submit">Save gang settings</button></form>`;
}
